environment:
  matrix:
    - PYTHON_VERSION: 3.6
      PYTHON: "C:\\Miniconda36-x64"

init:
  - "ECHO Python from %PYTHON%"
  - "ECHO Miniconda from %ANACONDA%"

install:
  # Python
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - python --version
  - python -m pip install --upgrade pip
  - python  -m pip --version
  - python -m pip install --upgrade wheel
  - python -m wheel version
  # Microsoft MPI (piggyback off of mpi4py appveyor setup scripts)
  - git clone https://github.com/mpi4py/mpi4py.git _mpi4py_
  - "powershell _mpi4py_\\conf\\ci\\appveyor\\install-msmpi.ps1"
  - "SetEnvMPI.cmd"
  # Check versions
  - python --version
  - python -m pip --version
  - "\"%MSMPI_BIN%\\mpiexec.exe\" -h"
  - "\"%MSMPI_BIN%\\mpiexec.exe\" -v"
  # Install package
  - python -m pip install -r test_requirements.txt
  - python -m pip install codecov
  - python setup.py develop

build: off

test_script:
  - pytest -v --doctest-modules src/pybnb
  - pytest -v --cov=pybnb --cov=examples --cov=src/tests

on_success:
  # Combine coverage reports over all subprocesses
  - "cd %BUILD_DIR%"
  - dir .cov*
  - "coverage combine %BUILD_DIR%"
  - codecov -X gcov
