environment:
  matrix:
    - PYTHON_VERSION: 3.6
      PYTHON: "C:\\Miniconda36-x64"

init:
  - "ECHO Python from %PYTHON%"
  - "ECHO Miniconda from %ANACONDA%"

install:
  # Python
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - python --version
  - python -m pip install --upgrade pip
  - python  -m pip --version
  - python -m pip install --upgrade wheel
  - python -m wheel version
  # Microsoft MPI (piggyback off of mpi4py appveyor setup scripts)
  - git clone https://github.com/mpi4py/mpi4py.git _mpi4py_
  - "powershell _mpi4py_\\conf\\ci\\appveyor\\install-msmpi.ps1"
  - "SetEnvMPI.cmd"
  - "SET PATH=%MSMPI_BIN%;%PATH%"
  # Check versions
  - python --version
  - python -m pip --version
  - mpiexec -help2
  # Install package
  - python -m pip install -r test_requirements.txt
  - python -m pip install codecov
  - python setup.py develop

build: off

test_script:
  - pytest -v --doctest-modules src/pybnb
  - pytest -v src/tests/mpi/test_heaps.py
  - pytest -v src/tests/mpi/test_misc.py
  - pytest -v src/tests/test_common.py
  - pytest -v src/tests/test_convergence_checker.py
  - pytest -v src/tests/test_dispatcher.py
  - pytest -v src/tests/test_examples.py
  - pytest -v src/tests/test_misc.py
  - pytest -v src/tests/test_node.py
  - pytest -v src/tests/test_package.py
  - pytest -v src/tests/test_priority_queue.py
  - pytest -v src/tests/test_problem.py
  - pytest -v src/tests/test_pyomo_tools.py
  - pytest -v src/tests/test_simple_problems.py
  - pytest -v src/tests/test_solver.py
#  - pytest -vvvv --cov=pybnb --cov=examples --cov=src/tests

on_success:
  # Combine coverage reports over all subprocesses
  - "cd %BUILD_DIR%"
  - dir .cov*
  - "coverage combine %BUILD_DIR%"
  - codecov -X gcov
