# travis CI config
cache: false
language: generic
services:
  - docker
env:
  global:
    - DH_ACCT_NAME=qkjqvazeqfjqftchxlgw
  matrix:
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi SLIM=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-mpich
    - IMAGE_NAME=python-mpi-builds:python_3.5-openmpi
    - IMAGE_NAME=python-mpi-builds:python_3.5-mpich
    - IMAGE_NAME=python-mpi-builds:python_2.7-openmpi
    - IMAGE_NAME=python-mpi-builds:python_2.7-mpich
    - IMAGE_NAME=python-mpi-builds:pypy_3-openmpi
    - IMAGE_NAME=python-mpi-builds:pypy_3-mpich
    - IMAGE_NAME=python-mpi-builds:pypy_2-openmpi
    - IMAGE_NAME=python-mpi-builds:pypy_2-mpich
before_install:
  - docker pull ${DH_ACCT_NAME}/${IMAGE_NAME}
  - export CI_ENV=`bash <(curl -s https://codecov.io/env)`
install:
 # start the container as root user for the install phase
  - export DOC_ID=`docker run -d -v $(pwd):$(pwd) -w $(pwd) --user root ${DH_ACCT_NAME}/${IMAGE_NAME} sleep 10000000000`
  - export DOC="docker exec ${CI_ENV} -e DH_ACCT_NAME -e IMAGE_NAME -e SLIM -e EXAMPLES ${DOC_ID}"
  - ${DOC} pip install -U pip setuptools wheel
  - ${DOC} python --version
  - ${DOC} pip --version
  - ${DOC} mpirun --version
  - ${DOC} pip install -r test_requirements.txt
  - ${DOC} pip install codecov
  - ${DOC} python setup.py install
########
  - ${DOC} bash -c 'echo `python -c "import runtests; print(runtests.__path__[0])"`/mpi/tester.py'
  - ${DOC} bash -c 'sed -i "s/assert(os.path.exists(self.TEST_DIR))/print(\"@@@@@@@@\", self.TEST_DIR)/g" `python -c "import runtests; print(runtests.__path__[0])"`/mpi/tester.py'
########
 # run the remainder of commands as non-root to avoid openmpi errors
  - export DOC="docker exec ${CI_ENV} -e DH_ACCT_NAME -e IMAGE_NAME -e SLIM -e EXAMPLES --user $(id -u) ${DOC_ID}"
script:
  - while sleep 9m; do echo "still running..."; done &
  - "[[ -z $SLIM ]] || bash .travis/test_slim.sh"
  - "[[ -n $SLIM ]] || bash .travis/test_parallel.sh"
  - kill %1
after_script:
  - ${DOC} find . -name "*.coverage*"
  - ${DOC} coverage combine
  - ${DOC} coverage report
  - ${DOC} codecov --env DH_ACCT_NAME IMAGE_NAME SLIM EXAMPLES
  - docker kill ${DOC_ID}
  - docker ps
