cache: false
language: python
services:
- docker
env:
  global:
    - DH_ACCT_NAME=qkjqvazeqfjqftchxlgw
  matrix:
    - IMAGE_NAME=python-mpi-builds:python_3.7-openmpi DEPLOY=1
    - IMAGE_NAME=python-mpi-builds:python_3.7-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.7-openmpi EXAMPLES=1 PYOMO_RELEASE=1
    - IMAGE_NAME=python-mpi-builds:python_3.7-openmpi SLIM=1
    - IMAGE_NAME=python-mpi-builds:python_3.7-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.5-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.5-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_2.7-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_2.7-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:pypy_3-openmpi
    - IMAGE_NAME=python-mpi-builds:pypy_3-mpich
    - IMAGE_NAME=python-mpi-builds:pypy_2-openmpi
    - IMAGE_NAME=python-mpi-builds:pypy_2-mpich
before_install:
  - docker pull ${DH_ACCT_NAME}/${IMAGE_NAME}
  - export CI_ENV=`bash <(curl -s https://codecov.io/env)`
  - export DOC_ID=`docker run -d -v $(pwd):$(pwd) -w $(pwd) ${DH_ACCT_NAME}/${IMAGE_NAME} sleep 10000000000`
  - export DOC="docker exec ${CI_ENV} -e DH_ACCT_NAME -e IMAGE_NAME -e SLIM -e EXAMPLES ${DOC_ID}"
install:
  - ${DOC} pip install -U pip setuptools wheel
  - ${DOC} python --version
  - ${DOC} pip --version
  - ${DOC} mpirun --version
  - |
    if ${DOC} python -c"import __pypy__" &> /dev/null
    then
       ${DOC} pip uninstall -y numpy
       ${DOC} pip install numpy==1.15.4
    fi
  - |
    if [ -z "$PYOMO_RELEASE" ]
    then
        ${DOC} git clone https://github.com/Pyutilib/pyutilib.git
        ${DOC} bash -c 'cd ./pyutilib && python setup.py install && cd .. && rm -r ./pyutilib'
        ${DOC} git clone https://github.com/Pyomo/pyomo.git
        ${DOC} bash -c 'cd ./pyomo && python setup.py install && cd .. && rm -r ./pyomo'
    fi
  - ${DOC} pip install -r test_requirements.txt
  - ${DOC} pip install codecov
  - ${DOC} python setup.py develop
script:
  - while sleep 9m; do echo "still running..."; done &
  - "[[ -z $SLIM ]] || bash .travis/test_slim.sh"
  - "[[ -n $SLIM ]] || bash .travis/test_parallel.sh"
  - kill %1
  - ${DOC} bash -c 'find . -name __pycache__ | xargs rm -rf'
  - ${DOC} bash -c 'find . -name "*.egg-info" | xargs rm -rf'
  - ${DOC} rm -rf .pytest_cache
after_script:
  - ${DOC} find . -name "*.coverage*"
  - ${DOC} coverage combine
  - ${DOC} coverage report
  - ${DOC} codecov --env DH_ACCT_NAME IMAGE_NAME SLIM EXAMPLES
  - docker kill ${DOC_ID}
  - docker ps
deploy:
  provider: pypi
  user: N2PG43fzLFB76ukPVpWD
  password:
    secure: "QRnY9dWGdzbRIb7iZnvgflRy91R3QMgwm6UlgVmdhlzbtoT/iJZ+2jMNpeZVM/GM5kjRti+OmMPgQTUqnC+NfvuTV9C+xyyFDMIAEPkKrnYiJZGWkCe9D9qxXoy2bqxnwcJeSk2kn9bQHUtEWv1D6osSIPoJheJ5Df8JuTfsG1JMuNb7JsfQhyZaOGOcMovExSfGh7BBC+aTfD0dF4Xn4yfx9ZPuGYUEsDz01Qny7VtIPcrIYE8EEV1ONo6KwCrHSx5bhWqvZM49w6NAl9PXUUKidMZvwU5aRvBHS0YHEE3LO1EK23rSiRe9P2k/GUQ8thvAUzDSIwav9DantrSKzzhOEO253JlccdPYQfIuQYKnOwpO92BdZo9nc35zCCQPm5LYaFY792YGoJ/AZGOgKUoFqHiMdsv2G/50GvgIclZvhO98S/v9NnBdJYRTQLNjTEvJoBvqbArnGuq4+Xl1kOWQc6EX/H8vpeynD/Wv6f4kbhLBwKUM/rfeR9kB/FaU/5bp64oDPP6xARZ492/iVdN7PNQRYfZpep0xy5b0AVmM3BZsBdOjsYx9d8iuD54u6T2IHdMDl+xZRdJtHJ5ImKC+x+k4EqbpiqxPOSSiTgF4BXswf8FW61J4NlY0sbday2mxehbwQ87lCBt+DFhtW2qKBNrRGKUeZ23Uc9F4NOg="
  distributions: sdist
  on:
    tags: true
    all_branches: true
    condition: $DEPLOY = 1
