# travis CI config
sudo: required
cache: false
language: generic
services:
  - docker
env:
  global:
    - DH_ACCT_NAME=qkjqvazeqfjqftchxlgw
  matrix:
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi SLIM=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-mpich
    - IMAGE_NAME=python-mpi-builds:python_3.5-openmpi
    - IMAGE_NAME=python-mpi-builds:python_3.5-mpich
    - IMAGE_NAME=python-mpi-builds:python_2.7-openmpi
    - IMAGE_NAME=python-mpi-builds:python_2.7-mpich
    - IMAGE_NAME=python-mpi-builds:pypy_3-openmpi
    - IMAGE_NAME=python-mpi-builds:pypy_3-mpich
    - IMAGE_NAME=python-mpi-builds:pypy_2-openmpi
    - IMAGE_NAME=python-mpi-builds:pypy_2-mpich
before_install:
  - docker pull ${DH_ACCT_NAME}/${IMAGE_NAME}
  - export DOC_ID_=`docker run -d -v $(pwd):$(pwd) -w $(pwd) ${DH_ACCT_NAME}/${IMAGE_NAME} sleep 10000000000`
  - export CI_ENV=`bash <(curl -s https://codecov.io/env)`
  - export DOC_="docker exec ${CI_ENV} -e DH_ACCT_NAME -e IMAGE_NAME -e SLIM -e EXAMPLES ${DOC_ID_}"
install:
  - ${DOC_} pip install -U pip setuptools wheel
  - ${DOC_} python --version
  - ${DOC_} pip --version
  - ${DOC_} mpirun --version
  - ${DOC_} pip install -r test_requirements.txt
  - ${DOC_} pip install codecov
  - ${DOC_} python setup.py develop
  - ${DOC_} rm -rf .coverage*
script:
  - while sleep 9m; do echo "still running..."; done &
  - "[[ -z $SLIM ]] || bash .travis/test_slim.sh"
  - "[[ -n $SLIM ]] || bash .travis/test_parallel.sh"
  - kill %1
after_script:
  - ${DOC_} find . -name "*.coverage*"
  - ${DOC_} coverage combine
  - ${DOC_} coverage report
  - ${DOC_} codecov --env DH_ACCT_NAME IMAGE_NAME SLIM EXAMPLES
  - docker kill ${DOC_ID_}
  - docker ps
