# travis CI config
cache: false
language: generic
services:
  - docker
env:
  global:
    - DH_ACCT_NAME=qkjqvazeqfjqftchxlgw
  matrix:
#    - IMAGE_NAME=python-mpi-builds:python_3.7-rc-openmpi
#    - IMAGE_NAME=python-mpi-builds:python_3.7-rc-mpich
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-openmpi SLIM=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.6-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.5-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_3.5-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_2.7-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:python_2.7-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:pypy_3-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:pypy_3-mpich EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:pypy_2-openmpi EXAMPLES=1
    - IMAGE_NAME=python-mpi-builds:pypy_2-mpich EXAMPLES=1
before_install:
  - docker pull ${DH_ACCT_NAME}/${IMAGE_NAME}
  - export CI_ENV=`bash <(curl -s https://codecov.io/env)`
  - export DOC_ID=`docker run -d -v $(pwd):$(pwd) -w $(pwd) ${DH_ACCT_NAME}/${IMAGE_NAME} sleep 10000000000`
  - export DOC="docker exec ${CI_ENV} -e DH_ACCT_NAME -e IMAGE_NAME -e SLIM -e EXAMPLES ${DOC_ID}"
install:
  - ${DOC} pip install -U pip setuptools wheel
  - ${DOC} python --version
  - ${DOC} pip --version
  - ${DOC} mpirun --version
  - ${DOC} git clone https://github.com/Pyutilib/pyutilib.git
  - ${DOC} bash -c "cd ./pyutilib && python setup.py install && cd .. && rm -r ./pyutilib"
  - ${DOC} git clone https://github.com/Pyomo/pyomo.git
  - ${DOC} bash -c "cd ./pyomo && python setup.py install && cd .. && rm -r ./pyomo"
  - ${DOC} pip install -r test_requirements.txt
  - ${DOC} pip install codecov
  - ${DOC} python setup.py develop
script:
  - while sleep 9m; do echo "still running..."; done &
  - "[[ -z $SLIM ]] || bash .travis/test_slim.sh"
  - "[[ -n $SLIM ]] || bash .travis/test_parallel.sh"
  - kill %1
after_script:
  - ${DOC} find . -name "*.coverage*"
  - ${DOC} coverage combine
  - ${DOC} coverage report
  - ${DOC} codecov --env DH_ACCT_NAME IMAGE_NAME SLIM EXAMPLES
  - docker kill ${DOC_ID}
  - docker ps
